%% poemAnalysis_main
% Analysis code for the Penn Online Evaluation of Migraine (POEM)
%
% Description:
%   This routine loads the .csv files generated by Qualtrics that have the
%   results of the migraine diagnostic pathway. The link the data for the
%   Aguirre lab can be found here:
%
%       https://upenn.co1.qualtrics.com/jfe/form/SV_4NQzKbssiT8qqVf
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clear variables
close all



%% Select the csv file to process
[rawFileName,rawFilePath] = uigetfile('*.csv','Select a Qualtrics csv file');


%% Figure out the number of columns
numColumns = size(readmatrix(fullfile(rawFilePath,rawFileName)),2);
formatString = repmat('%q',1,numColumns');


%% load and pre-process thisDataSheet, returning table "T"
[T, notesText] = poemAnalysis_preProcess(fullfile(rawFilePath,rawFileName),'formatString',formatString);


%% classify headache based upon table T
diagnosisTable = poemAnalysis_classify( T );


%% Select the location to write
[saveFileName,saveFilePath] = uiputfile('*.xlsx','Location to save diagnosis table',fullfile(rawFilePath,'diagnosisTable.xlsx'));
writetable(diagnosisTable,fullfile(saveFilePath,saveFileName),'Range','A4','WriteRowNames',true)

