%% poemAnalysis_main
% Analysis code for the Penn Online Evaluation of Migraine (POEM)
%
% Description:
%   This routine loads the .csv files generated by Qualtrics that have the
%   results of the migraine diagnostic pathway. The link the data for the
%   Aguirre lab can be found here:
%
%       https://upenn.co1.qualtrics.com/jfe/form/SV_4NQzKbssiT8qqVf
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clear variables
close all

numColumns = input('How many data columns are present? (press enter to attempt to guess from file)');
formatString = repmat('%q',1,numColumns');

%% Select the csv file to process
[rawFileName,rawFilePath] = uigetfile('*.csv');

%% load and pre-process thisDataSheet, returning table "T"
[T, notesText] = poemAnalysis_preProcess(fullfile(rawFilePath,rawFileName),'formatString',formatString);

%% classify headache based upon table T
diagnosisTable = poemAnalysis_classify( T );

%% Select the location to write
[saveFileName,saveFilePath] = uiputfile('*.xlsx');

writetable(diagnosisTable,fullfile(saveFilePath,saveFileName),'Range','A4','WriteRowNames',true)

