function responseTable = poemAnalysis_perception( T )
%
% This function takes the table variable "T" and extracts responses to
% some questions

numSubjects = size(T,1);

responseTypes={'ageInYears',...
    'zipFirstThree',...
    'P_SL1_Sunlight',...
    'P_SL2_Overcast',...
    'P_SL3_Store',...
    'P_SL4_Bathroom',...
    'P_FL1_Strobe',...
    'P_FL2_Trees',...
    'P_FL3_Fluorscent',...
    'P_FL4_Screen',...
    'P_GL1_Headlights',...
    'P_GL2_LampNight',...
    'P_GL3_IndirectDay',...
    'P_GL4_Reflecting',...
    'P_TA1_Hair',...
    'P_TA2_Hat',...
    'P_TA3_Cold',...
    'P_TA4_Eye',...
    'Photic_Sneeze_Subj',...
    'Photic_Sneeze_Relative',...
    'Menstral_HA',...
    'Motion_Sickness',...
    'MIDAS_1',...
    'MIDAS_2',...
    'MIDAS_3',...
    'MIDAS_4',...
    'MIDAS_5',...
    'HeadacheDays',...
    'Feedback'};

columnQuestionText={'What is your age (in years)?',...
    'What are the first three numbers of your zip-code? Example: If your zipcode is 19104, enter 191.',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Bright sunlight when outdoors',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - An overcast day when outdoors',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Typical lighting in an office or grocery store',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Bright indoor lighting in a kitchen and/or bathroom',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Strobe light at a club or concert',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Sunlight moving through trees when in a car or train',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Fluorscent lighting',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Computer and/or television screen',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Headlights from oncoming traffic at night',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - A single, bright light fixture or lamp at night',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Indirect, bright light from the sun or a lamp in your peripheral vision during the day',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Light reflecting off the surface of water or windows',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Combing, braiding, and/or washing your hair',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Wearing a hat, eyeglasses and/or sunglasses',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Cold things on your face (e.g., breathing through your nose on a cold day, placing ice packs on your forehead)',...
    'Please rate the discomfort (i.e. pain or unpleasant sensation) you have for the following experiences.  If you sometimes have headaches, please provide the rating for when you DO NOT have a headache. - Having something in your eye (e.g. dust or grit, an eyelash, a contact lens)',...
    'Do you tend to sneeze when you step out of a dark room into bright sunlight?',...
    'Do your parents or other first-degree relatives have this sneeze reflex?',...
    'Do you usually get headaches around your menstrual periods?',...
    'Did you get motion sick easily as a child?',...
    'Please answer the following questions about ALL of the headaches you have had over the last 3 months. Select your answer in the box next to each question. Select zero if you did not have the activity in the last 3 months. - 1. On how many days in the last 3 months did you miss work or school because of your headaches?',...
    'Please answer the following questions about ALL of the headaches you have had over the last 3 months. Select your answer in the box next to each question. Select zero if you did not have the activity in the last 3 months. - 2. How many days in the last 3 months was your productivity at work or school reduced by half or more because of your headaches? (Do not include days you counted in question 1 where you missed work or school.)',...
    'Please answer the following questions about ALL of the headaches you have had over the last 3 months. Select your answer in the box next to each question. Select zero if you did not have the activity in the last 3 months. - 3. On how many days in the last 3 months did you not do household work (such as housework, home repairs and maintenance, shopping, caring for children and relatives) because of your headaches?',...
    'Please answer the following questions about ALL of the headaches you have had over the last 3 months. Select your answer in the box next to each question. Select zero if you did not have the activity in the last 3 months. - 4. How many days in the last 3 months was your productivity in household work reduced by half of more because of your headaches? (Do not include days you counted in question 3 where you did not do household work.)',...
    'Please answer the following questions about ALL of the headaches you have had over the last 3 months. Select your answer in the box next to each question. Select zero if you did not have the activity in the last 3 months. - 5. On how many days in the last 3 months did you miss family, social or leisure activities because of your headaches?',...
    'On how many days in the last 3 months did you have a headache? (If a headache lasted more than 1 day, count each day.)',...
    'Is there a question that we should have asked about sensitivity to light or touch in people with headaches? Tell us what we should have asked!'};

variableType = {'int16',...
    'int16',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'likert',...
    'string',...
    'string',...
    'string',...
    'string',...
    'int16',...
    'int16',...
    'int16',...
    'int16',...
    'int16',...
    'int16',...
    'string',...
    };

% Anonymous function to strip out white space and line feeds / returns
stripWhite = @(str) regexprep(str,'\r\n|\n|\r',' ');

% Pull the QuestionText out of the table properties
QuestionText=T.Properties.UserData.QuestionText;

responseTable = table('Size',[numSubjects size(responseTypes,2)],'VariableTypes',strrep(variableType,'likert','int8'));
responseTable.SubjectID = T.SubjectID;


for thisSubject = 1:numSubjects
    for qq = 1:length(responseTypes)
        
        % Test if there is a column in the table for each question
        questionExist = cellfun(@(x) strcmp(stripWhite(columnQuestionText{qq}),stripWhite(x)), QuestionText);
        
        % QuestionExist will all be true of a column was found for each question
        if sum(questionExist)==1
            % Identify which columns of the table contain the relevant questions.
            questionColumnIdx = find(questionExist);
            % Copy over the response string
            responseVal = [];
            switch variableType{qq}
                case 'int16'
                    responseVal = {str2double(cell2mat(table2cell(T(thisSubject,questionColumnIdx))))};                    
                case 'string'
                    responseVal = T(thisSubject,questionColumnIdx);
                case 'likert'
                    tempVal = table2cell(T(thisSubject,questionColumnIdx));
                switch tempVal{1}
                    case 'Not uncomfortable'
                        responseVal = {1};
                    case 'Slightly uncomfortable'
                        responseVal = {2};
                    case 'Moderately uncomfortable'
                        responseVal = {3};
                    case 'Very uncomfortable'
                        responseVal = {4};
                    case 'Extremely uncomfortable'
                        responseVal = {5};
                    otherwise
                        error('Not a valid Likert response')
                end
            end
            foo=1;
            responseTable(thisSubject,qq) = responseVal;
        end
    end
    
end % loop over subjects

responseTable.Properties.VariableNames(1:length(responseTypes)) = responseTypes;
responseTable.Properties.RowNames=T.Properties.RowNames;

end % function



