%% poemAnalysis_main
% Analysis code for the Penn Online Evaluation of Migraine (POEM), version
% 3
%
% Description:
%   This routine loads the .csv files generated by Qualtrics that have the
%   results of the migraine diagnostic pathway. The link the data for the
%   Aguirre lab can be found here:
%
%       https://upenn.co1.qualtrics.com/jfe/form/SV_4NQzKbssiT8qqVf
%
%   Subsequent functions called from this main script are responsible for
%   pre-processing of the data fields and then implementing the headache
%   classification pathway.
%

%% Housekeeping
clear variables
close all

%% Set paths to data and output
dataDir = '/Users/carlynpattersongentile/Documents/data/poem/';
analysisDir = '/Users/carlynpattersongentile/Documents/analysis/poem/';

% Set the output filenames
outputResultExcelName=fullfile(dataDir, 'POEM_v3.0_January 8, 2024_17.32.csv');
rawDataSheets={'POEM_v3.0_January 8, 2024_17.32.csv'};

% get the full path to thisDataSheet
thisDataSheetFileName=fullfile(dataDir, rawDataSheets{1});


%% load and pre-process thisDataSheet, returning table "T"
[T, notesText] = poemAnalysis_preProcess_v3(thisDataSheetFileName);


%% classify headache based upon table T
diagnosisTable = poemAnalysis_classify( T );
writetable(diagnosisTable,outputResultExcelName,'Range','A4','WriteRowNames',true)

