
% qualtricsAnalysis_main
%
% This routine loads the .csv files generated by Qualtrics that have the
% results of the migraine diagnostic pathway.
%
%  https://upenn.co1.qualtrics.com/jfe/form/SV_4NQzKbssiT8qqVf
%

%% Housekeeping
clear variables
close all

[~, userName] = system('whoami');
userName = strtrim(userName);
dropboxDir = ...
    fullfile('/Users', userName, '/Dropbox (Aguirre-Brainard Lab)');

%% Set paths to data and output
%qualtricsDataDir = '/MELA_subject/QualtricsData/';
qualtricsDataDir = '/MELA_analysis/surveyMelanopsinAnalysis/Qualtrics/';
analysisDir = '/MELA_analysis/surveyMelanopsinAnalysis/Qualtrics/';

% Set the output filenames
outputResultExcelName=fullfile(dropboxDir, analysisDir, 'MELA_QualtricsHeadacheResults.xlsx');
rawDataSheets={'PHAT 1B_August 15, 2017_15.18.csv'};

% Loop through the datasheets

% get the full path to thisDataSheet
thisDataSheetFileName=fullfile(dropboxDir, qualtricsDataDir, rawDataSheets{1});

% load and pre-process thisDataSheet, returning table "T"
[T, notesText] = qualtricsAnalysis_preProcess(thisDataSheetFileName);

% classify headache
diagnosisTable = qualtricsAnalysis_classifyHeadache( T );
writetable(diagnosisTable,outputResultExcelName,'Range','A4','WriteRowNames',true)
